name: flutter_dashboard
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"  


dependencies:
  flutter:
    sdk: flutter

  #State manegement
  get: ^4.6.1

  #google fonts
  google_fonts: ^2.3.1

  #chart ui
  fl_chart: ^0.45.0

  
  flutter_svg: ^1.0.3
  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/images/
      - assets/icons/

